add `whenPaused` modifier
Blueberryfi/blueberry-staking pull request #23
Opened 2024-03-31 17:38 UTC by Gornutz

# Description
Add the `whenPaused` modifer to admin setters to ensure no mismatch of pools and stable asset.

## Type of change

- [X] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [X] The diff is legible and has no extraneous changes
- [X] Complex code has been commented, including external interfaces
- [X] Tests are included for all code paths
- [X] The base branch is either `master`, or there's a description of how to merge

## Issue Resolution

2024-04-01 22:18 UTC, 0xSpraggins commented
I think it would be a better approach to remove the `setStableAsset` function all together and set `stableAsset` within the `setUniswapV3Pool` function adding an extra parameter with that stable asset and cross referencing to verify that the pool accurately contains the proper token. This way we don't need the `whenPaused` modifier, can reduce the number of calls the admin needs to make and guarantee that the Uniswap pool and our `stableAsset` match.

2024-04-18 19:33 UTC, 0xSpraggins requested changes

2024-04-18 19:33 UTC, 0xSpraggins commented on src/BlueberryStaking.sol
> +        }
```suggestion
bool blbIsToken0 = IUniswapV3Pool(_uniswapPool).token0() == address(blb)

If (blbIsToken0) {
    address token1 = IUniswapV3Pool(_uniswapPool).token1();
    If (token1 != _stableAsset) revert InvalidStableAsset();
    stableAsset = token1
 } else {
    address token0 = IUniswapV3Pool(_uniswapPool).token0();
    If (token0 != _stableAsset) revert InvalidStableAsset();
    stableAsset = token0
}
```

We can optimize this future will less external calls and comparisons and then reuse blbIsToken0 when setting `uniswapV3Info`.

2024-04-18 19:33 UTC, 0xSpraggins commented on src/BlueberryStaking.sol
> +        stableAsset = IERC20(_stableAsset);
```suggestion
```
Can be removed if we make the optimization above

2024-04-18 19:33 UTC, 0xSpraggins commented on src/interfaces/IBlueberryStaking.sol
> +        uint256 _observationPeriod
```suggestion
        address uniswapPool,
        address stableAsset,
        uint8 decimals,
        uint256 observationPeriod
```

Small format fix

2024-04-18 19:33 UTC, 0xSpraggins commented on test/Control.t.sol
Would be good to also add a tests that expects to revert when setting a stable token that is not in the Uniswap pair

2024-04-18 19:52 UTC, 0xSpraggins requested changes

2024-04-18 19:52 UTC, 0xSpraggins commented on src/BlueberryStaking.sol
>              blbIsToken0: IUniswapV3Pool(_uniswapPool).token0() == address(blb)
```suggestion
            blbIsToken0: blbIsToken0
```
U can reuse the variable from line 749

2024-04-18 19:52 UTC, 0xSpraggins commented on test/Control.t.sol
> +        vm.expectRevert();
```suggestion
        vm.expectRevert(IBlueberryStaking.InvalidStableAsset.selector);
```

2024-04-18 20:10 UTC, 0xSpraggins approved these changes

2024-04-19 17:06 UTC, IAm0x52 approved these changes
Fix looks good. setStableAsset has been removed. setUniswapV3Pool now sets stableAsset as well as pool to prevent any mismatch.

2024-04-19 17:08 UTC, merged